first_django/first_app/urls.py
from django.contrib import admin
from django.urls import path
from first_app import views

app_name="first_app"

urlpatterns = [
    path("sign_up/",views.FormView,name="Sign_up"),
    path("login/",views.LoginView,name="Login")
]

first_django/first_django/urls.py
from django.contrib import admin
from django.urls import path,include
from first_app import views,urls

urlpatterns = [
    path("",views.index,name="index"),
    path("admin/", admin.site.urls),
    path("user/",include("first_app.urls"))
]

first_django/first_app/models.py
from django.db import models

# Create your models here.
class Accounts(models.Model):
    Full_name = models.CharField(max_length = 128)
    Username = models.CharField(max_length = 16,unique=True)
    e_Mail= models.EmailField(unique=True)
    password = models.CharField(max_length=32)
    
    def __str__(self) -> str:
        return super().__str__()


class Articles(models.Model):
    Username = models.ForeignKey(Accounts,on_delete=models.CASCADE)
    Article_id = models.IntegerField(unique = True)
    Article_Content = models.TextField()
    Date_Posted = models.DateTimeField(auto_now_add = True)
     
    def __str__(self) -> str:
        return super().__str__()


class Comments(models.Model):
    Article_id = models.ForeignKey(Articles,on_delete=models.CASCADE)
    Comment_id = models.IntegerField(unique = True)
    Comment_Username = models.CharField(max_length = 16,unique=True)
    Comment = models.TextField()

    def __str__(self) -> str:
        return super().__str__()

class Articles_Details(models.Model):
    Article_id = models.ForeignKey(Articles,on_delete=models.CASCADE,)
    Likes = models.IntegerField()
    Re_Posts = models.PositiveIntegerField()
    Post_Comments = models.ForeignKey(Comments,on_delete=models.CASCADE)

    def __str__(self) -> str:
        return super().__str__()

first_django/first_app/forms.py
from django import forms
from django.core import validators
from .models import Accounts,Articles,Articles_Details,Comments
import re

class SignUpForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())
    class Meta():
        model = Accounts
        fields = "__all__"
  
class LoginForm(forms.Form):
    Username = forms.CharField(max_length='128')
    Passowrd = forms.CharField(max_length= '32',widget=forms.PasswordInput())

    def clean(self,):
        super(LoginForm,self).clean()
        Username = self.cleaned_data.get("Username")
        Password = self.cleaned_data.get("Password")
        try:
            user = Accounts.objects.get(Username=Username)
            if Password!=user.Password:
                self._errors['Password'] = self._error_class['Password Doesn\'t Match']
        except:
            self._error["Username"] = self._error_class[f"User with {Username} USername Can't be Found"]
        finally:    
            return self.cleaned_data

first_django/first_app/views.py
from django.shortcuts import render
from django.http import HttpResponse
from . import forms

def index(request):
    return render(request,'first_app\index.html')

def FormView(request):
    form= forms.SignUpForm()
    if request.method =="POST":
        form= forms.SignUpForm(request.POST)
        if form.is_valid():
            form.save()
            return index(request)

    return render(request,"first_app/formpage.html",{"form":form})

def LoginView(request):
    Login = False
    form = forms.LoginForm()
    if request.method =="POST":
        form= forms.LoginForm(request.POST)
        if form.is_valid():
            Login = True
    return render(request,"first_app/loginpage.html",{"form":form,"Login":Login})

first_django/templates/first_app/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title></title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
</head>
<body class="text-light bg-dark">
    <nav class="navbar navbar-expand-lg" style="background-color:rgb(118, 255, 173)">
        <div class="container-fluid">
          <a class="navbar-brand" href="{% url 'index' %}">HOME</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
            <div class="navbar-nav">
              <a class="nav-link active" aria-current="page" href="{% url 'first_app:Login' %}">Login</a>
              <a class="nav-link active" aria-current="page" href="{% url 'first_app:Sign_up' %}">Sign Up</a>
              <a class="nav-link" href="#">Forgot Password</a>
              <a class="nav-link disabled">Delete Account</a>
            </div>
          </div>
        </div>
    </nav>
    {% block body_block %}
    {% endblock %}
</body>
</html>

first_django/templates/first_app/formpage.html
<!DOCTYPE html>
{% extends "first_app/base.html"%}
{%block body_block %}
<div class="position-absolute top-50 start-50 translate-middle">
    <div class="border border-4 border-opacity-25 rounded-4">
        <div class="container px-10 text-center">
            <br><br>
        <form method="post">
            <div class="mb-3">
                {{ form.as_p }}
                {% csrf_token %}
                <div class="mb-3 form-check">
                    <input type="checkbox" class="form-check-input" id="exampleCheck1" required>
                    <label class="form-check-label" for="exampleCheck1"><p>I Agree to Terms & Comditions</p></label></div>
                <button type="submit" class="btn btn-outline-primary">Submit</button>
            </div>
        </form>
        <br>
    </div></div></div>
{% endblock %}

first_django/templates/first_app/index.html
<!DOCTYPE html>
{% extends "first_app/base.html"%}
{%block body_block %}
    
        <div class="position-absolute top-50 start-50 translate-middle">
            <div class="border border-4 border-opacity-25 rounded-4">
                <div class="container px-10 text-center">
                <br><h1>Welcome</h1> <br>
                    <br>
                    <br>
                    <br>
                <h2 class="text-success"><a class="btn btn-outline-success btn-lg" role="link" href="{% url 'first_app:Login' %}">Login</a> into Existing Account <br></h2>
                    <p></p>
                <h2 class="text-info">or <a class="btn btn-outline-info btn-lg" role="link" href="{% url 'first_app:Sign_up' %}">Sign up</a> for new Account </h2>
            </div>
        </div>
    </div>
{% endblock %}

first_django/templates/first_app/loginpage.html
<!DOCTYPE html>
{% extends "first_app/base.html"%}
{%block body_block %}
<div class="position-absolute top-50 start-50 translate-middle">
    <div class="border border-4 border-opacity-25 rounded-4">
        <div class="container px-10 text-center">
            <br><br>

        {% if Login %} 
            <h1>Logged In Successfully ;) </h1>
            <a class="btn btn-outline-primary btn-lg" role="link" href="{% url 'index' %}">Return to Index Page</a><br><br>
        {% else %}
            <form method="post">
                <div class="mb-3">
                    {{ form.as_p }}
                    {% csrf_token %}
                    <div class="mb-3 form-check">
                        <input type="checkbox" class="form-check-input" id="exampleCheck1">
                        <label class="form-check-label" for="exampleCheck1"><p>Keep me Signed In</p></label></div>
                    <button type="submit" class="btn btn-outline-primary">Submit</button>
                </div>
            </form>
        {% endif %}
        <br>
    </div></div></div>
{% endblock %}